### ISSUE TITLE
Проблемы в настройках pom.xml. Настройки пути к chromedriver.exe.

### ISSUE THREAD

**Issue by TikhomirovSergey** [xabaev/tinkoffTestProject#2]
Настройка будет работать только на определенной машине WINDOWS.

Предлагаю: 
- убрать настройку 
```xml
                    <systemPropertyVariables>
                        <webdriver.chrome.driver>C://sgrid/chromedriver.exe</webdriver.chrome.driver>
                    </systemPropertyVariables>
```

- Использовать [webdrivermanager](https://github.com/bonigarcia/webdrivermanager) для установки бинарных файлов.

**Comment by xabaev** [comment]
Добавил webdrivermanager + вынес настройки браузера в @BeforeTest
