### ISSUE TITLE
Уйти от хардкода к универсальным методам.

### ISSUE THREAD

**Issue by AndrewCharykov** [xabaev/tinkoffTestProject#3]
У тебя реализован метод 
```
public void clickBank() {
        $(By.xpath("//span[@data-qa-file='FirstMenu'][contains(text(),'Банк')]")).click();
    }
```
а что будет если тебе нужно будет кликнуть по Инвестициям , страхованию, мобайл и тд.?

Необходимо уйти от хардкода к универсальным методам.
Например что-то такое:
```
public void selectFirstMenu(String firstMenuLink ) {
        $(By.xpath("//span[@data-qa-file='FirstMenu'][contains(text(),'firstMenuLink ')]")).click();
    }
```

**Comment by xabaev** [comment]
А каким образом тогда переходить к открытой странице в тесте? 
На каждый переход страницы инициализировать новый класс? Это кажется не совсем правильным.

**Comment by xabaev** [comment]
Перевел основные методы к универсализации
