### ISSUE TITLE
Дизайн теста

### ISSUE THREAD

**Issue by TikhomirovSergey** [xabaev/tinkoffTestProject#4]
Проблемы:
- метод большой, трудно читаемый.
- проблема такого метода в том, что тест может упасть в самом начале. Это приведет к тому, что 
все остальные проверки не пройдут. В реальной жизни это приводит к тому, что пока фиксится одна бага, никто не знает про остальные.

Нужно:
- подумать над дизайном автотеста. Его надо разбить на несколько тестовых методов/классов. 
- проверку вводов невалидных значений в поля можно выполнить в виде параметризированного  автотеста. Метод должен уместиться в 1-3 строчки
- сформировать представление об аннотациях junit (`@Before`, `@After`, `@RunWith` и т.д.)

**Comment by xabaev** [comment]
Выделено два теста - основной процесс и проверка валидации.
Проверка невалидных значений приведена к нормальному виду.
